version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./server/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  client:
    build:
      dockerfile: ./Dockerfile
    command: yarn dev --host 0.0.0.0
    volumes:
      - ./src:/app/src

  server:
    build:
      dockerfile: ./server/Dockerfile
    command: node app.js
    volumes:
      - ./server/app.js:/app/app.js

  prometheus:
    image: prom/prometheus
    volumes:
      - ./server/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_DASHBOARDS_DEFAULT_HOME_REFRESH_INTERVAL=200ms
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=200ms
    volumes:
      - ./server/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
