version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  server:
    build:
      dockerfile: Dockerfile
    command: node app.js
    volumes:
      - ./:/app

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_DASHBOARDS_DEFAULT_HOME_REFRESH_INTERVAL=200ms
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=200ms
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
